# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fraud-detect-terraform-state-us-east-1-dev"
    dynamodb_table = "fraud-detect-terraform-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
