name: Destroy the IaC in AWS

on:
  workflow_dispatch:
    inputs:
      destroy_s3:
        description: 'Destroy S3 Bucket?'
        required: true
        default: 'false'

jobs:
  destroy-iac:
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:latest
      options: --entrypoint /bin/bash

    env:
      IMAGE_TAG: ${{ vars.IMAGE_TAG }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Initialize terragrunt
        run: |
          terragrunt init
      
      - name: Initialize each module
        run: |
          for module in vpc s3_bucket ecr_ecs ecr_lambda kinesis_untagged kinesis_tagged glue_table cloudwatch_dashboard kinesis_firehose sagemaker_media sagemaker_text ecs_cluster ecs_processor lambda; do
            echo "Processing module: $module"
            echo "--------------------------------------------------------------------------"
            cd live/dev/$module
            if [ "$module" = "vpc" ]; then
              terragrunt apply --auto-approve
            else
              terragrunt init
            fi
            cd - > /dev/null
          done

      - name: Destroy Lambda
        run: |
          cd live/dev/lambda
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy ECS Processor
        run: |
          cd live/dev/ecs_processor
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy ECS Cluster
        run: |
          cd live/dev/ecs_cluster
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy SageMaker Text
        run: |
          cd live/dev/sagemaker_text
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy SageMaker Media
        run: |
          cd live/dev/sagemaker_media
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy Kinesis Firehose
        run: |
          cd live/dev/kinesis_firehose
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy CloudWatch Dashboard
        run: |
          cd live/dev/cloudwatch_dashboard
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy Glue Table
        run: |
          cd live/dev/glue_table
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy Kinesis Tagged
        run: |
          cd live/dev/kinesis_tagged
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy Kinesis Untagged
        run: |
          cd live/dev/kinesis_untagged
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy ECR Lambda
        run: |
          cd live/dev/ecr_lambda
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy ECR ECS
        run: |
          cd live/dev/ecr_ecs
          terragrunt destroy --auto-approve --non-interactive

      - name: Check if s3 bucket should be destroyed
        run: echo "destroy_s3=${{ inputs.destroy_s3 }}"

      - name: Destroy S3 Bucket
        if: ${{ inputs.destroy_s3 == 'true' }}
        run: |
          cd live/dev/s3_bucket
          terragrunt destroy --auto-approve --non-interactive

      - name: Destroy VPC
        run: |
          cd live/dev/vpc
          terragrunt destroy --auto-approve --non-interactive
